### ISSUE TITLE
Rate limiting Batch.libretexts.org

### ISSUE THREAD

**Issue by ymdahi** [LibreTexts/Libretext#152] opened 2021-10-07 02:01 UTC
## Problem
According to MindTouch, there is a 5000 calls per 5 minute threshold on their API service.
batch.libretexts.org (159.65.100.70) seems to be exceeding this threshold, and is therefore being blocked automatically.

This may/may not be impacting other services, such as transclusions (https://github.com/LibreTexts/Libretext/issues/153).

## Context
Batch hosts nodePrint, a microservice that generates PDFs of books/pages within LibreTexts.

We were notified recently (Sept 28) by MindTouch devs that this server had been blocked for exceeding the limit.

## Possible Solution(s)

* Limit the number of calls
* Use batch/queuing to better manage calls

## Next Steps

* Document nodePrint as best as we can
* Find a way to limit calls

**Comment by ymdahi** [comment] 2021-10-07 02:01
@Miniland1333 : any comments would be helpful.

**Comment by ymdahi** [comment] 2021-10-21 01:13
TODO:

- [ ] check in with MT to see if batch.LT has been blocked since the changes in #153 
- [ ] implement changes in line72 in nodePrint.js as per Henry's comments

**Comment by Miniland1333** [comment] 2021-12-02 20:09
![image](https://user-images.githubusercontent.com/12994749/144495055-a83b22ef-7b3a-4538-8b33-b7fa4723d900.png)
FYI it looks like batching for Chemistry has been broken for some time. I think you need to adjust schedule.js in order to get this working again with the lower rate.

https://chem.libretexts.org/Under_Construction/Development_Details/Admin_Tools/API_Dashboard

**Comment by Miniland1333** [comment] 2022-09-03 21:26
Duplicate of https://github.com/LibreTexts/Libretext/issues/169

**Closed by Miniland1333** 2022-09-03 21:26 UTC
Labels: bug
