### ISSUE TITLE
Remixer Intermittent Loading Issues

### ISSUE THREAD

**Issue by ethanaturner** [LibreTexts/Libretext#149] opened 2021-09-25 20:37 UTC
### Description
Some users are experiencing issues loading the OER Remixer as of late August 2021. This issues appears to be present across all libraries and does not seem to be limited to a specific device/browser/network configuration.

### Current Insights
Certain Firefox versions are reporting `Loading failed for the <script> with source "https://cdn.libretexts.net/github/LibreTextsMain/Henry%20Agnew/Remixer/bundle.js"`. The script appears in the Inspect > Network tab and has a `200` response with no apparent issues. The script **does not**, however, appear in the Inspect > Debugger tab with other files loaded from LibreTexts CDN.

### Affected Environments
The issue primarily appears to affect Firefox (versions 89 & 91) and Chrome, especially on macOS systems [prior to Catalina](https://en.wikipedia.org/wiki/MacOS_version_history#Releases).

### Possible Fixes
It is possible that this is an issue emanating from Cloudflare (the service powering LibreTexts CDN) potentially due to SSL certificate issues. It may also help to manually trigger a re-sync with Cloudflare and purge its cache.

_In general, no evidence indicates this is an issue with Remixer source code itself._

### Suggestion for Affected Users
Users should try to:

- Clear their browser cache
- Access Remixer from an unrestricted network (e.g., their home network)
- For Firefox users, try using Troubleshoot Mode (Menu > Help > Troubleshoot Mode)
- **If possible and feasible, update both their operating system and browser to the most recent versions available**

If users are still experiencing issues, especially after updating, please [contact LibreTexts](mailto:info@libretexts.org) so we can gather more information.

**Comment by Miniland1333** [comment] 2021-09-27 03:44
One thing that I've long suspected but have not yet proven is that the intermediary DigitalOcean cache may occasionally be corrupting the files. If this is what is occuring, the solution would be to go into the DigitalOcean control panel for the librefiles2 space and Purge Cache.
![image](https://user-images.githubusercontent.com/12994749/134842418-a0244dcd-763b-4d3f-b14b-90529dab33ab.png)

**Comment by Miniland1333** [comment] 2021-09-27 03:45
I do agree that the issue is quite intermittent and thus difficult to trace the source.

**Comment by ymdahi** [comment] 2021-09-27 13:35
Issues seems to be affecting Windows systems as well.

### October 27 6:32am PDT:
@ethanaturner @Miniland1333: I've purged the cache for `librefiles2/github/LibreTextsMain/Henry Agnew/Remixer/`. Please help confirm that this had the desired affect.

**Comment by ethanaturner** [comment] 2021-09-27 16:12
@ymdahi That seems to have worked. Remixer loads fine on both Chrome & Firefox on the systems that were having issues.

**Comment by ymdahi** [comment] 2021-09-27 16:35
Wonderful! @ethanaturner, since you're on point for this ticket, can you please update Delmar.

**Comment by ymdahi** [comment] 2021-09-30 01:12
@ethanaturner Any luck reproducing the error? From what I understand there are still about a dozen people experience this issue?

I've just purged the the cache for `.../Remixer/bundle.js` on Cloudflare - this didn't seem to have any affect on my end.

We can bypass Cloudflare to test, but I would only want to do that for a small operating window.

Thoughts?

**Comment by ethanaturner** [comment] 2021-09-30 02:18
@ymdahi Now Chrome 94 on Windows 10 is reporting `net::ERR_HTTP2_PROTOCOL_ERROR` and it looks like the `cf-cache-status` is `EXPIRED` (meanwhile its `HIT` on my machine). I tried purging the cache again, no go. Maybe bypassing Cloudflare to test is a good idea...

**Comment by ymdahi** [comment] 2021-09-30 15:27
@Miniland1333 : Remixer libraries are only needed for that one page, right? e.g. `Under_Construction/Development_Details/OER_Remixer`. 

As a potential remedy, I'm thinking we serve that file locally instead of CDN.

**Comment by Miniland1333** [comment] 2021-09-30 15:32
I do think this is something that we should try by using the link directly from the digitalocean spaces. If the issue persists, then the issue is related to DigitalOcean spaces itself.

**Comment by ymdahi** [comment] 2021-09-30 15:42
Is there a way to bypass DO Spaces too? e.g. upload the libraries to LibreTexts server?

**Comment by ymdahi** [comment] 2021-09-30 18:27
@Miniland1333 : does this screenshot mean anything to you?

https://imgur.com/a/SZAeVzb

**Comment by ymdahi** [comment] 2021-10-07 02:38
Closing this ticket for now.

## Solution
Bypassed Cloudflare CDN for Remixer library (bundle.js). Seems to have address the issue.

**Closed by ymdahi** 2021-10-07 02:38 UTC
Labels: bug, Remixer, CDN
